version: 2
updates:

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
    open-pull-requests-limit: 3
    reviewers:
      - kieran-ryan
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    commit-message:
      prefix: "fix: "
